// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qqnzqdrnqvoblyqeeoed.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxbnpxZHJucXZvYmx5cWVlb2VkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2MjA2NTgsImV4cCI6MjA2NzE5NjY1OH0.QHgz7C1qPJTCuz1O02CSAJFLR6YDfPngYPYKX8T2Dvs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);